# The Fourier Transform

***

In this notebook, you will learn about complex numbers and the Fourier Transform.

In [2]:
# Numerical arrays.
import numpy as np

# Fourier Transforms
import scipy

<h2 style="color: rgb(0, 91, 94);">Complex Numbers</h2>

<hr style="border-top: 1px solid rgb(0, 91, 94);" />

Hello, world!

## Fast Fourier Transforms

***

https://docs.scipy.org/doc/scipy/tutorial/fft.html

$$
y[k] = \sum_{n=0}^{N-1} \exp^{-2 \pi j \frac{kn}{N}} x[n]
$$

In [4]:
x = np.array([1.0, 2.0, 1.0, -1.0, 1.5])
x

array([ 1. ,  2. ,  1. , -1. ,  1.5])

In [5]:
y = scipy.fft.fft(x)
y

array([ 4.5       -0.j        ,  2.08155948-1.65109876j,
       -1.83155948+1.60822041j, -1.83155948-1.60822041j,
        2.08155948+1.65109876j])

In [7]:
yinv = scipy.fft.ifft(y)
yinv

array([ 1. +0.j,  2. +0.j,  1. +0.j, -1. +0.j,  1.5+0.j])

<hr style="border-top: 1px solid rgb(0, 91, 94);" />

<h2 style="color: rgb(0, 91, 94);">End</h2>